package ORM;
// Generated 05-mar-2020 17:57:41 by Hibernate Tools 4.3.1



/**
 * Tortuga generated by hbm2java
 */
public class Tortuga  implements java.io.Serializable {


     private int id;
     private Cuidador cuidador;
     private String apodo;
     private Long peso;
     private Boolean hiberna;
     private Integer edad;

    public Tortuga() {
    }

	
    public Tortuga(int id) {
        this.id = id;
    }
    public Tortuga(int id, Cuidador cuidador, String apodo, Long peso, Boolean hiberna, Integer edad) {
       this.id = id;
       this.cuidador = cuidador;
       this.apodo = apodo;
       this.peso = peso;
       this.hiberna = hiberna;
       this.edad = edad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuidador getCuidador() {
        return this.cuidador;
    }
    
    public void setCuidador(Cuidador cuidador) {
        this.cuidador = cuidador;
    }
    public String getApodo() {
        return this.apodo;
    }
    
    public void setApodo(String apodo) {
        this.apodo = apodo;
    }
    public Long getPeso() {
        return this.peso;
    }
    
    public void setPeso(Long peso) {
        this.peso = peso;
    }
    public Boolean getHiberna() {
        return this.hiberna;
    }
    
    public void setHiberna(Boolean hiberna) {
        this.hiberna = hiberna;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


